In [2]:
import numpy as np

In [3]:
A = [[1,2,3],[4,5,6],[7,8,9]]
B = [[1,1,1],[2,2,2],[3,3,3]]
C = [[2,3,4],[6,7,8],[10,11,12]]

def add_arrays(A, B):
    C = []
    for i in range(len(A)):
        temp = []
        C.append(temp)
        for j in range(len(A[i])):
            temp.append(A[i][j] + B[i][j])
    return C

assert (add_arrays(A, B) == np.array(C)).all()

In [8]:
x, y = np.arange(0,50,2).reshape(5,5), 2*np.eye(5)
print("x is" + "\n" + str(x))
print("")
print("y is" + "\n" + str(y))
print("")
print("np.dot(x,y) is matrix multiplication")
print(np.dot(x,y))
print("")
print("np.matmul(x,y) is matrix multiplication")
print(np.matmul(x,y))
print("")
print("np.multiply(x,y) is element-wise multiplication")
print(np.multiply(x,y))

x is
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]

y is
[[2. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 2.]]

np.dot(x,y) is matrix multiplication
[[ 0.  4.  8. 12. 16.]
 [20. 24. 28. 32. 36.]
 [40. 44. 48. 52. 56.]
 [60. 64. 68. 72. 76.]
 [80. 84. 88. 92. 96.]]

np.matmul(x,y) is matrix multiplication
[[ 0.  4.  8. 12. 16.]
 [20. 24. 28. 32. 36.]
 [40. 44. 48. 52. 56.]
 [60. 64. 68. 72. 76.]
 [80. 84. 88. 92. 96.]]

np.multiply(x,y) is element-wise multiplication
[[ 0.  0.  0.  0.  0.]
 [ 0. 24.  0.  0.  0.]
 [ 0.  0. 48.  0.  0.]
 [ 0.  0.  0. 72.  0.]
 [ 0.  0.  0.  0. 96.]]


In [9]:
def linearCombination(A, B, a, b):
    alinear = np.multiply(A,a)
    blinear = np.multiply(B,b)
    return alinear + blinear
    pass

vector1 = np.array([1,2])
vector2 = np.array([5,6])
scalar1 = 3
scalar2 = 10

assert (np.array([53, 66]) == linearCombination(vector1, vector2, scalar1, scalar2)).all()

In [11]:
def get_column_as_1d(A, col_number):
    data = np.array(A)
    return data[:, col_number:col_number+1]
    pass

def get_row_as_1d(A, row_number):
    data = np.array(A)
    return data[row_number:row_number+1]
    pass

A = [[1,2,3],[4,5,6],[7,8,9]] 
print(get_column_as_1d(A, 1)) # [2,5,8]
print("")
print(get_row_as_1d(A, 2)) # [7,8,9]

[[2]
 [5]
 [8]]

[[7 8 9]]


Modulo essentials

In [12]:
import time

s = time.time()
ans = 1002583 ** 939001 % 2003951
t = time.time()

print("calculating {} took {:.2f} seconds".format(ans, t-s))

calculating 1590868 took 3.44 seconds


In [13]:
s = time.time()
ans = pow(1002583,939001,2003951)
t = time.time()

print("calculating {} operation took {:.2f} seconds".format(ans, t - s))

calculating 1590868 operation took 0.00 seconds
