# Numpy warmup
Make sure you have numpy installed.

In [2]:
!python -m pip install numpy````

You might need to restart the notebook after running the command above

In [16]:
import numpy as np

## Exercise 1, add two arrays together
We have two arrays: A and B

`A = [[1,2,3],[4,5,6],[7,8,9]]`

`B = [[1,1,1],[2,2,2],[3,3,3]]`

`C = [[2,3,4],[6,7,8],[10,11,12]]`

Your code should work for general matrices, not just the ones above. Use `np.array`, not `np.matrix`. Your function will need to cast the above to np.arrays. If you get stuck ask chatGPT!

In [6]:
A = [[1,2,3],[4,5,6],[7,8,9]]
B = [[1,1,1],[2,2,2],[3,3,3]]
C = [[2,3,4],[6,7,8],[10,11,12]]

In [83]:
def add_arrays(A, B):
    C = []
    for i in range(len(A)):
        temp = []
        C.append(temp)
        for j in range(len(A[i])):
            temp.append(A[i][j] + B[i][j])
    return C

In [84]:
assert (add_arrays(A, B) == np.array(C)).all()

What does the `.all()` do? The above operation does an elementwise equality check. It checks that every item in the array is `True`.

In [18]:
print(np.array([True, True, True]).all())
print(np.array([False, True, True]).all())

True
False


## Exercise 2, element-wise and matrix multiplication
When dealing with numpy arrays, we need to be clear if we are doing matrix multiplication or elementwise multiplication.

Your task is to write functions for both. Numpy supports both, figure out how it does it. Don't implement it manually

Elementwise = multiplying each element positiion with each other. 

In [ ]:
def matrix_multiply(A, B):
    return np.dot(A,B)

In [37]:
x, y = np.arange(0,50,2).reshape(5,5), 2*np.eye(5)
print(np.multiply(x,y))
print("gap")
print(np.dot(x,y))
print("gap")
print(np.matmul(x,y))

[[ 0.  0.  0.  0.  0.]
 [ 0. 24.  0.  0.  0.]
 [ 0.  0. 48.  0.  0.]
 [ 0.  0.  0. 72.  0.]
 [ 0.  0.  0.  0. 96.]]
gap
[[ 0.  4.  8. 12. 16.]
 [20. 24. 28. 32. 36.]
 [40. 44. 48. 52. 56.]
 [60. 64. 68. 72. 76.]
 [80. 84. 88. 92. 96.]]
gap
[[ 0.  4.  8. 12. 16.]
 [20. 24. 28. 32. 36.]
 [40. 44. 48. 52. 56.]
 [60. 64. 68. 72. 76.]
 [80. 84. 88. 92. 96.]]


In [ ]:
def element_wise_multiply(A, B):
    return np.multiply(A,B)

To avoid giving hints, we won't supply the test case here. But you can check your work online!

## Exercise 3, the dot product
The dot product is another kind of multiplication.

We expect [1,2,3,4] $\cdot$ [1,2,3,4] to be equal (1 * 1) + (2 * 2) + (3 * 3) + (4 * 4) = 1 + 4 + 9 + 16 = 20

Figure out numpy's implementation and do it. Don't implement it manually.

In [ ]:
def dot_product(A, B):
    return np.dot(A,B)

In [47]:
# Vectors = Arrays in python
vector_from_list = np.array([1, 2, 3, 4, 5])
# print("Vector from list:", vector_from_list)

zero_vector = np.zeros(5)
# print("Zero vector:", zero_vector)

ones_vector = np.ones(5)
# print("Ones vector:", ones_vector)

range_vector = np.arange(0, 10, 2)  # Start, stop, step
# print("Range vector:", range_vector)

# # Elementwise addition
# sum_vector = vector_from_list + ones_vector
# print("Sum:", sum_vector)

# # Elementwise subtraction
# diff_vector = vector_from_list - ones_vector
# print("Difference:", diff_vector)

# Elementwise multiplication
product_vector = vector_from_list * 5
print("Product:", product_vector)

Product: [ 5 10 15 20 25]


## Exercise 4, linear combinations

A linear combination is a Vector multiplied by a constant plus another Vector multiplied by a constant.

Aa + Bb = C (A, B, C are vectors, a and b are scalars)

Compute the linear combination in the general case.

In [4]:
def linearCombination(A, B, a, b):
    alinear = np.multiply(A,a)
    blinear = np.multiply(B,b)
    return alinear + blinear
    pass

In [5]:
vector1 = np.array([1,2])
vector2 = np.array([5,6])
scalar1 = 3
scalar2 = 10

assert (np.array([53, 66]) == linearCombination(vector1, vector2, scalar1, scalar2)).all()

## Exercise 5, modular arithmetic
Modular arithmetic is important in cryptography. The challenge here is to compute the modular inverse of 15 % 1223. 

That is 5 * x % 1223 == 1.

The basic syntax for this is the same as other languages

In [ ]:
(5 * 16) % 1223

In [ ]:
(5 + 1219) % 1223

Be very careful, because the mod operator sometimes takes precedence!

Hint: Python 3.8 has a very nice way to do this

In [7]:
# Compute the modular multiplicative inverse of 5 modulo 1223
x = pow(5, -1, 1223)

# Print the result
print("The modular multiplicative inverse of 5 modulo 1223 is:", x)

# Verify the result
if (5 * x) % 1223 == 1:
    print("Verification successful: 5 * x % 1223 = 1")
else:
    print("Verification failed")


The modular multiplicative inverse of 5 modulo 1223 is: 734
Verification successful: 5 * x % 1223 = 1


## Exercise 6, Column and Row Slicing

Numpy let's you select rows and columns from matrices. For example, given

```
[[1,2,3],
 [4,5,6],
 [7,8,9]] 
```
 
you can retrive [2,5,8] or [7,8,9] conveniently. Implement those below:

In [63]:
def get_column_as_1d(A, col_number):
    data = np.array(A)
    return data[:, col_number:col_number+1]
    pass

def get_row_as_1d(A, row_number):
    data = np.array(A)
    return data[row_number:row_number+1]
    pass

In [2]:
A = [[1,2,3],[4,5,6],[7,8,9]] 

In [64]:
print(get_column_as_1d(A, 1)) # [2,5,8]

[[2]
 [5]
 [8]]


In [62]:
print(get_row_as_1d(A, 2)) # [7,8,9]

[[7 8 9]]
